// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Olwe.Data;

#nullable disable

namespace Olwe.Data.Migrations
{
    [DbContext(typeof(OlweContext))]
    [Migration("20220619095504_add some mod configs")]
    partial class addsomemodconfigs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Olwe.Data.Entities.Guild.GuildConfigEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("Olwe.Data.Entities.Guild.GuildEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Olwe.Data.Entities.Guild.GuildModConfigEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("AntiPhishingEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("PhishingInfractionType")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.ToTable("ModConfigs");
                });

            modelBuilder.Entity("Olwe.Data.Entities.Guild.InfractionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<ulong>("EnforcerId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<ulong>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("UserNotified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Infractions");
                });

            modelBuilder.Entity("Olwe.Data.Entities.Guild.GuildConfigEntity", b =>
                {
                    b.HasOne("Olwe.Data.Entities.Guild.GuildEntity", "Guild")
                        .WithOne("Config")
                        .HasForeignKey("Olwe.Data.Entities.Guild.GuildConfigEntity", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Olwe.Data.Entities.Guild.GuildModConfigEntity", b =>
                {
                    b.HasOne("Olwe.Data.Entities.Guild.GuildEntity", "Guild")
                        .WithOne("ModConfig")
                        .HasForeignKey("Olwe.Data.Entities.Guild.GuildModConfigEntity", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Olwe.Data.Entities.Guild.InfractionEntity", b =>
                {
                    b.HasOne("Olwe.Data.Entities.Guild.GuildEntity", "Guild")
                        .WithMany("Infractions")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Olwe.Data.Entities.Guild.GuildEntity", b =>
                {
                    b.Navigation("Config")
                        .IsRequired();

                    b.Navigation("Infractions");

                    b.Navigation("ModConfig")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
